name: install
description: "Install dependencies"

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: corepack enable
      shell: bash
    - uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"
    - run: pnpm -v
      shell: bash
    - run: pnpm install --frozen-lockfile
      shell: bash
