on:
  workflow_call:
  workflow_dispatch:
  push:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - run: pnpm start
